# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: sayThanks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install pipfile
        run: |
          pipenv install

      - name: pipenv shell
        run: |
          pipenv run python ./NexuxPHP/sayThanks.py
        env:
          COOKIE: ${{ secrets.COOKIE }}

      - name: commit
        run: |
          git config --global user.email wdjoys@hotmail.com
          git config --global user.name xiaocao
          git add ./NexuxPHP/config.ini
          git commit -m "update config.ini" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
