# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: qiandao

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 3 * * *
    # 国家时间 3点 北京时间11点触发
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install pipfile
        run: |
          pipenv install

      - name: pipenv shell
        run: |
          pipenv run python run.py nexusphp signin
        env:
          COOKIE: ${{ secrets.CONFIG }}
